# Generated by Django 5.2.2 on 2025-07-25 08:45

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_maincategory_rename_category_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('price', models.FloatField(max_length=100, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/original/', verbose_name='Изображение')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='images/products/thumbnail/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='categories.subcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': ('Товар',),
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
